int Get_para(int argc, char **argv,
	     char *file_pdb, char *chain,
	     char *file_pdb_list, char *pdb_dir,
	     char *file_ali, char *file_dna,	
	     char *tnm, char *tnm_mut_para, 
	     char **file_str_mut, int *N_str_mut, int *IWT,
	     int *MEANFIELD,  int *MF_COMP,
	     int *OPT_REG, int *SCORE_CV, float *REG,
	     char *file_str, float *TEMP, float *sU1,
	     float *sC0, float *sC1, int *REM3, float *SEC_STR,
	     int *REMUT, int *GET_FREQ, float *freq_nuc,
	     float *trans_ratio, float *kCpG, float *TWONUC,
	     int *PRINT_E, char *EXCHANGE, char *MATRIX,
	     int *FORMAT, int *ALL_MUTS,
	     int *IT_MAX, int *Samples, int *NEUTRAL, int *N_pop, 
	     int *OPT_LAMBDA, float *LAMBDA, float *DG_OPT, char *MODEL,
	     char *dir_out);
